# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/board.xdc

# Block Designs: bd/bluetooth_demo/bluetooth_demo.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo || ORIG_REF_NAME==bluetooth_demo} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_microblaze_0_0/bluetooth_demo_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_microblaze_0_0 || ORIG_REF_NAME==bluetooth_demo_microblaze_0_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_microblaze_0_axi_periph_0/bluetooth_demo_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_microblaze_0_axi_periph_0 || ORIG_REF_NAME==bluetooth_demo_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_microblaze_0_axi_intc_0/bluetooth_demo_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_microblaze_0_axi_intc_0 || ORIG_REF_NAME==bluetooth_demo_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_microblaze_0_xlconcat_0/bluetooth_demo_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_microblaze_0_xlconcat_0 || ORIG_REF_NAME==bluetooth_demo_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_mdm_1_0/bluetooth_demo_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_mdm_1_0 || ORIG_REF_NAME==bluetooth_demo_mdm_1_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_clk_wiz_1_0/bluetooth_demo_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_clk_wiz_1_0 || ORIG_REF_NAME==bluetooth_demo_clk_wiz_1_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_rst_clk_wiz_1_100M_0/bluetooth_demo_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==bluetooth_demo_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_sensor_fusion_axi_0_0/bluetooth_demo_sensor_fusion_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_sensor_fusion_axi_0_0 || ORIG_REF_NAME==bluetooth_demo_sensor_fusion_axi_0_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_axi_uartlite_0_0/bluetooth_demo_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_axi_uartlite_0_0 || ORIG_REF_NAME==bluetooth_demo_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_axi_uartlite_1_0/bluetooth_demo_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_axi_uartlite_1_0 || ORIG_REF_NAME==bluetooth_demo_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_mux_9x1_0_0/bluetooth_demo_mux_9x1_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_mux_9x1_0_0 || ORIG_REF_NAME==bluetooth_demo_mux_9x1_0_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_hex_display_controll_0_1/bluetooth_demo_hex_display_controll_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_hex_display_controll_0_1 || ORIG_REF_NAME==bluetooth_demo_hex_display_controll_0_1} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_xlconcat_0_0/bluetooth_demo_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_xlconcat_0_0 || ORIG_REF_NAME==bluetooth_demo_xlconcat_0_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_xbar_0/bluetooth_demo_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_xbar_0 || ORIG_REF_NAME==bluetooth_demo_xbar_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_dlmb_v10_0/bluetooth_demo_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_dlmb_v10_0 || ORIG_REF_NAME==bluetooth_demo_dlmb_v10_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_ilmb_v10_0/bluetooth_demo_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_ilmb_v10_0 || ORIG_REF_NAME==bluetooth_demo_ilmb_v10_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_dlmb_bram_if_cntlr_0/bluetooth_demo_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==bluetooth_demo_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_ilmb_bram_if_cntlr_0/bluetooth_demo_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==bluetooth_demo_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/bluetooth_demo/ip/bluetooth_demo_lmb_bram_0/bluetooth_demo_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bluetooth_demo_lmb_bram_0 || ORIG_REF_NAME==bluetooth_demo_lmb_bram_0} -quiet] -quiet

# XDC: bd/bluetooth_demo/bluetooth_demo_ooc.xdc
